services:
  db:
    image: mariadb:noble
    volumes:
      - db-data:/var/lib/mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: examplepassword
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: examplepassword

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress-data:/var/lib/wordpress:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: examplepassword
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "8090:80"

volumes:
  db-data:
  wordpress-data:
